### ISSUE TITLE
Press button change to dark theme manually, it flashes to dark for 1 second then reverses back to light

### ISSUE THREAD

**Issue by samsong** [oskarsh/Yin-Yang#101]
Kubuntu 21.10
KDE Plasma 5.23.0

When press the "dark" theme (which I set correctly in settings as breeze-dark), it flashes to the dark theme but only 1 second then reverses back to light.

can you tell me how to share logs with you to debug further?
Or is there a fix known?

**Comment by samsong** [comment]
OK I ran yin-yang from terminal & here is the log what happens when press dark button:

Changing theme in plugin System
QDBusConnection: error: could not send signal to service "" path "//home/z/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals
Changing theme in plugin System
QDBusConnection: error: could not send signal to service "" path "//home/z/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/z/.kde/share/config/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/z/.kde/share/config/kdeglobals

**Comment by samsong** [comment]
Possibly related to issue #92 or #88

**Comment by samsong** [comment]
Found the problem. It's not a 2nd instance. The "scheduled" feature was activated.
When try to press manually change theme from light to dark (during daytime)
The theme changes
then the same instance activates it's "scheduled" feature and changes it to the current timezone (light) theme.

This is why it changes back after 1 second.

I think this is probably something should be changed in the code to either:
1) disable the schedule feature when the user manually click light or dark
2) disable the schedule feature *activation* when the user manually click light or dark, BUT keep running the schedule and activate at the next timezone switch.

Either one of these options will resolve the issue more cleanly & not confuse the user.

**Comment by l0drex** [comment]
Should be fixed with the switch to systemd. It listens to config changes and stops the unit if the mode was changed to manually.
