### ISSUE TITLE
Firefox integration not working

### ISSUE THREAD

**Issue by yaomtc** [oskarsh/Yin-Yang#104]
I installed the Firefox extension, and in Yin & Yang's settings, Firefox is checked, with the two themes set as "Light" and "Dark". However, this doesn't do anything for me. If the Light theme is currently enabled, and I click "Dark" in Yin & Yang, Firefox does not change. If I restart Firefox, its theme is still light. Likewise if Firefox is using a Dark theme, Yin & Yang will not change it.

I have installed Yin & Yang from the AUR on Arch Linux today, and I am using Plasma, with the Plasma Integration add-on (I don't think this does anything with theming, though)

**Comment by l0drex** [comment]
Turns out I already fixed it, but didn't commit and updated the extension. Should work in a few days

**Comment by l0drex** [comment]
Updated is now public, if it now works for you then please close this issue

**Comment by yaomtc** [comment]
Yes, upon restart of Firefox the theme successfully changes. Is there a way to get Firefox to change without restarting it?

**Comment by l0drex** [comment]
In theory, it should work without a restart. You only need to restart if your config changed

**Comment by yaomtc** [comment]
Hmm, not sure why it's not working without a restart, as I haven't been changing the configuration. Maybe something to do with how Firefox is configured on my end, or the build from the Arch Linux repos vs some other builds
