### ISSUE TITLE
Support for Discord

### ISSUE THREAD

**Issue by yaomtc** [oskarsh/Yin-Yang#109]
Discord does have a "sync with computer" option under User Settings > Appearance > Theme, but at least on Plasma (Arch Linux) it doesn't work. Not sure why.

Has anyone figured out where Discord looks for the "sync with computer" setting, or found a good way to make it work? I looked for a config file but couldn't find one.

**Comment by l0drex** [comment]
I think thats because Discord is based on electron, which uses the engine of chromium. Chromium has a bug where the prefers-dark-theme check does not work.
