### ISSUE TITLE
Not using native widget style (there is a workaround)

### ISSUE THREAD

**Issue by alxlg** [oskarsh/Yin-Yang#11]
GUI doesn't use native Qt widget style (Breeze by default in Plasma) but uses Fusion.

Uninstalling PyQt5 with PIP:

`pip3 uninstall PyQt5`

and installing PyQt5 with distro packages (tested on Ubuntu/KDE Neon, package name `python3-pyqt5`) is a workaround for now. See screenshot below:

![immagine](https://user-images.githubusercontent.com/26327475/54625802-42dbbb80-4a70-11e9-8068-4b088189801d.png)

**Comment by daehruoydeef** [comment]
Just tested the workaround and it worked, will be implemented with Yin-Yang 3.0. Thanks

**Comment by l0drex** [comment]
Since every distro uses different package managers, it is really difficult to use them. Instead, I made a note of that in the installation section of the readme.
