### ISSUE TITLE
Support icon theme

### ISSUE THREAD

**Issue by AlexandreMarkus** [oskarsh/Yin-Yang#110]
I would like to be able to choose different icon themes for light/dark

**Comment by l0drex** [comment]
Which icons do you mean? Do you use Gnome, KDE or something else? Or do you mean an application?

**Comment by AlexandreMarkus** [comment]
> Which icons do you mean? Do you use Gnome, KDE or something else? Or do you mean an application?

I mean all applications icons. I use KDE.

**Comment by l0drex** [comment]
Ok, this was already requested in #50
