### ISSUE TITLE
is it possible to run Yin-Yang in background without running the window ?

### ISSUE THREAD

**Issue by QuakeString** [oskarsh/Yin-Yang#111]
I'm trying out Yin-Yang, and its almost serve my purpose, but I have to open it everything I want to change, so it essentially became same effort as going to setting and change global theme.
Is it possible to run in background so it change theme based on time ?

**Comment by l0drex** [comment]
Yes, you just need to enable _scheduled_ in the settings and set the time you want.
To start the script without the gui, you just pass the option -s to the command. That way you can add it to your autostart programs.

**Comment by JaHIY** [comment]
The option `-s` is not available in the current version!

**Comment by l0drex** [comment]
Yes, it now uses systemd, so you just need to enable them and it should work.

**Comment by JaHIY** [comment]
> Yes, it now uses systemd, so you just need to enable them and it should work.

Thanks. I have run the command `systemctl --user enable yin_yang.timer` , and it works now.

**Comment by major-mayer** [comment]
Ahh great, thanks for the hint.
It would be nice, if one could add this to the wiki.
Before, I just added Yin-Yang to the autostart list of my system and wondered why the theme changes are not applied.
