### ISSUE TITLE
Interested in maintaining the project

### ISSUE THREAD

**Issue by l0drex** [oskarsh/Yin-Yang#124]
Hey, I read that you are searching for a new maintainer. I would be interested!

**Comment by oskarsh** [comment]
Hey @l0drex that is great to hear! I really appreciate that you have been so active over the last years with helping the development of this Application and I am very comfortable handing this project over to you!
Feel free to take over this Project and create the necessary pull requests and features that you like! 

I think in terms of discover ability its best to keep this repository here and add new Bug fixes, improvements and features. You should already have all the necessary rights to approve and merge PRs. 
My idea of this project was always to create a simple go-to solution for automatic theme switching on Linux. It all started with a simple shell script and evolved to the application you can find know. I always valued form follows function and tried to create a tool that fulfills the user needs without it getting in the way. 
Thank you again for taking this over, much appreciation. ❤️❤️❤️

**Comment by oskarsh** [comment]
Please update the README.md and remove the search for maintainer if you are ready to take this over!

**Comment by l0drex** [comment]
Thank you so much for your work! When I first discovered this project, I was amazed that this is possible and immediately wanted to know how it works. I read through your code and learned a lot. Since I knew python from university, I realized this was a good opportunity to finally contribute some code to the open source world. Now I'm happy to continue your work :smile: 

However, I think I will stay with Qt and improve the UI as much as possible, since I don't know anything about Flutter.
My plan for now is to introduce a class for handling configs, which should make it easier to use. Then I will update the UI and fix the layout and allow translations.

**Comment by l0drex** [comment]
> Please update the README.md and remove the search for maintainer if you are ready to take this over!

I can't push to master right now, it's a protected branch.

**Comment by oskarsh** [comment]
I've removed the branch protection so that you can commit directly to master. I would suggest that you always create a new branch and a PR when you want to release a new feature. That way the master history is much cleaner and its easier to track the code where bugs are happening.

**Comment by l0drex** [comment]
Yes, I will make a new beta branch where I collect everything before the next release. Thanks :+1:
