### ISSUE TITLE
Q: Faiing to install Manjaro Sikaris 22.0.0 - ImportError suntime despite dependency satisfied?

### ISSUE THREAD

**Issue by wanageeska** [oskarsh/Yin-Yang#130]
Hi,
After cloning the repo and trying to run from command line with  yin-yang --toggle I get the following error:

```
Traceback (most recent call last):
File "/opt/yin-yang/main.py", line 12, in <module>
from src import yin_yang
File "/opt/yin-yang/src/yin_yang.py", line 16, in <module>
from src.config import Modes, config, plugins
File "/opt/yin-yang/src/config.py", line 15, in <module>
from suntime import Sun, SunTimeException
ImportError: cannot import name 'Sun' from 'suntime' (unknown location)
```
The dependency is satisfied as far as I can tell; however, because this is happening in config.py the config_path and yin_yang.json file are never created.

Could someone please help me out here?

Screenshot of terminal output:
![image](https://user-images.githubusercontent.com/17569679/193486078-fa1dace9-cd73-4218-9270-247f81b29831.png)

**Comment by l0drex** [comment]
Can you try to install suntime as a normal user: `pip install suntime`?

**Comment by l0drex** [comment]
Maybe try the following:
1. Create a venv in your cloned folder
3. Install all dependencies
4. Try to run Yin & Yang 

```
python3 -m venv /path/to/your/clone
pip3 install -r requirements.txt
./main.py
```

**Comment by bphd** [comment]
```python
Traceback (most recent call last):                                                                                                  
  File "/opt/yin-yang/main.py", line 13, in <module>
    from src import daemon_handler
  File "/opt/yin-yang/src/daemon_handler.py", line 8, in <module>
    from src.config import ConfigWatcher, config
  File "/opt/yin-yang/src/config.py", line 15, in <module>
    from suntime import Sun, SunTimeException
ModuleNotFoundError: No module named 'suntime'
```

**Comment by kki0t** [comment]
> ```python
> Traceback (most recent call last):                                                                                                  
>   File "/opt/yin-yang/main.py", line 13, in <module>
>     from src import daemon_handler
>   File "/opt/yin-yang/src/daemon_handler.py", line 8, in <module>
>     from src.config import ConfigWatcher, config
>   File "/opt/yin-yang/src/config.py", line 15, in <module>
>     from suntime import Sun, SunTimeException
> ModuleNotFoundError: No module named 'suntime'
> ```

Unrelated.

You can fix this by following [this fix](https://www.reddit.com/r/archlinux/comments/136uxj8/comment/jirdbal/?context=3), according to this [AUR comment](https://aur.archlinux.org/packages/yin-yang#comment-913667).
