### ISSUE TITLE
Thunderbird buggy behavior

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#132]
Hey there!
I've noticed a buggy behavior while using Thunderbird. When I switch theme with yin-yang, the only thing that changes is the upper toolbar's font color (see screenshot 1). Only when I alt-tab to other app, and then go back, the upper toolbar is rendered correctly (see screenshot 2). The rest of the app is sadly not switched at all, unless I close & open the window. Is there something that can be done about that?

I know that there is a Firefox extension to be used with yin-yang, but it seems to be working about half a times. If I'm not mistaken, Firefox & Thunderbird uses both GTK, on which the switching works just fine. Maybe it is connected to this warning, which I get when I run `yin-yang -t`

```
QDBusConnection: error: could not send signal to service "" path "//home/jukka/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/jukka/.config/kdedefaults/kdeglobals
QDBusConnection: error: could not send signal to service "" path "//home/jukka/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/jukka/.config/kdedefaults/kdeglobals
```

Using:
 - Arch Linux x86_64
 - KDE Plasma 5.25.5
 - master branch of yin-yang
 - Thunderbird 102.3.1

Thanks for helping me out!

**Comment by l0drex** [comment]
For me, it works. I was using the flatpak version of thunderbird, which is 102.3.2. Can you try that?

Maybe it's related to [this bug](https://bugs.kde.org/show_bug.cgi?id=446074). Since then, Yin & Yang just runs the command twice. Can you please check if you get the same behavior when running the following manually:

```
lookandfeeltool -a org.kde.breeze.desktop
lookandfeeltool -a org.kde.breezedark.desktop
lookandfeeltool -a org.kde.breezedark.desktop
```

**Comment by JokaJukka** [comment]
Sadly, no. I've tried multiple times, but apps refuse to change theme.

But, I've tried the flatpak version of the app and it switches instantly, after single command.

What is weird though, is that when I was installing flatpak version, I uninstalled the native one. After reinstallation, the issue seems gone - Firefox & Thunderbird works flawlessly...
