### ISSUE TITLE
No module named 'systemd'

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#135]
When using the latest release, following error happens when trying to start up the app:
```
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 11, in <module>
    from systemd import journal
ModuleNotFoundError: No module named 'systemd'
```

But I do have systemd on my system.

**Comment by l0drex** [comment]
You need `python-systemd` installed via pacman (or the package manager of your distro). Unfortunately, it's impossible to install via pip, so the installation script can't do it.

**Comment by JokaJukka** [comment]
Okay then. I'll add the dependency to AUR then.

Could you please point this out? As I haven't found this information anywhere. (and also the install command is slightly outdated).

**Comment by l0drex** [comment]
I wrote this in the wiki in the packaging instructions [here](https://github.com/oskarsh/Yin-Yang/wiki/Packaging), but I admit its not very accessible.

I also added it to the README and put a message in the install script.
