### ISSUE TITLE
Segmentation fault when starting app

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#137]
Problem with latest stable & beta releases - when running, console throws out this error:
`/usr/bin/yin-yang: line 3: 61791 Segmentation fault      (core dumped) python3 -O /opt/yin-yang/main.py "$@"`

**Comment by l0drex** [comment]
If you have installed `pyside6` from pacman, try to install `shiboken6` from pacman as well.

**Comment by JokaJukka** [comment]
Looks like my python installation was messed up (as I was switching from pip-based to pacman-based installation). However I fixed it, somehow.
