### ISSUE TITLE
No such schema “org.gnome.gedit.preferences.editor”

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#140]
Hey,
minor problem with the 3.2.0 release - when typing `yin-yang -t` in the console, this message shows up:  
`No such schema “org.gnome.gedit.preferences.editor”`  

I don't have gedit installed - I'm using KDE Plasma & VSCode.

Thanks for help!

**Comment by JokaJukka** [comment]
My fault - this is not the cause of the issue.

However, it seems that the upgrade to v3.2.0 purged my previous configuration.

**Comment by l0drex** [comment]
What exactly happened to your config?
