### ISSUE TITLE
Minor UI tweaks

### ISSUE THREAD

**Issue by JokaJukka** [oskarsh/Yin-Yang#141]
Hey,
this is a small list of minor graphic bugs/oddities that I've encountered with the version 3.2. Nothing critical, just stuff that I think would make the app better looking:
- When the app is opened by default, the plugins tab is slightly larger than the window itself, and thus the horizontal scrollbar appears. I suppose that the window should be slightly larger, or the content itself should stop shrinking on smaller window widths (see 1st screenshot below).
![image](https://user-images.githubusercontent.com/48550439/199599510-cc21d7ee-feab-4c21-8afb-3f808aef7d88.png)
- "Custom" input field has black text on black background - unlike the rest of the sections, which have correctly white color on dark background (see 2nd screenshot below).
- Disabled input field has changed background & text color, but disabled selector and disabled button has only changed text color. I think it would be less confusing if this would be united (see 2nd screenshot below) - so change the background on selector too.
![image](https://user-images.githubusercontent.com/48550439/199600732-97160789-262f-4ca3-b46d-58f9a207694c.png)

Everything was encountered on Arch Linux laptop, 1920x1080px (no scaling), with KDE Plasma 5.26.2.

**Comment by l0drex** [comment]
The bug with the window being smaller then the plugin widgets was there since the ui update, I didn't figure out how to fix that yet.

The colors are all (except the brave inputs) defined by the theme, nothing I can change.

**Comment by chase9** [comment]
If the coloring is a wontfix, than this would be resolved by #148

**Comment by l0drex** [comment]
#148 is now released, so I will close this now
