### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by daemonspudguy** [oskarsh/Yin-Yang#144]
Syntax error from daemon_handler.py `Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 13, in <module>
    from src import daemon_handler
  File "/opt/yin-yang/src/daemon_handler.py", line 52
    match change_values['key']:
`

**Comment by l0drex** [comment]
You need at least python 10 to run it. Update all your packages, that should hopefully fix it.
