### ISSUE TITLE
[Improvement] Better way to set gtk theme for KDE desktop (DBUS)

### ISSUE THREAD

**Issue by BruceZhang1993** [oskarsh/Yin-Yang#154]
According to [source code](https://github.com/KDE/plasma-workspace/blob/v5.26.90/kcms/style/gtkpage.cpp) of plasma-workspace, this is a better way to set gtk theme for KDE environment.

The advantage of this method: The gtk theme will also be applied to running gtk applications, no restart needed.

example of shell script: 
```shell
# with dbus-send
dbus-send --dest=org.kde.GtkConfig /GtkConfig org.kde.GtkConfig.setGtkTheme string:Materia-light
# with qdbus
qdbus org.kde.GtkConfig /GtkConfig org.kde.GtkConfig.setGtkTheme Materia-light
```

Service: org.kde.GtkConfig
Object path: /GtkConfig
Method: org.kde.GtkConfig.setGtkTheme
Param: [Theme name]

**Comment by l0drex** [comment]
Great suggestion, thank you! I will add this in the next release
