### ISSUE TITLE
[Improvement] Make time numbers directly editable, please

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#156]
Entering switch times in the Custom Schedule would be easier if one could just use `select all` in the time field + four `number keys`. 
Or, even better, just place the cursor *anywhere* in there, and type four digits to enter: "1234" => `12:34`. (This implies automatic  `select all` after the click.)
Edit: After _tabbing_ into the fields the 'four numbers' entering works, but moving the cursor back for corrections does not work.

**Comment by l0drex** [comment]
I understand the annoyance, but I'm just using the standard Qt inputs. I don't think I could fix that easily, and would like to keep the code as simple as possible.
You can file a bug to Qt if you want.

**Comment by noyannus** [comment]
I understand. Not a big nuisance anyway, one uses the input not too frequently.
