### ISSUE TITLE
[Improvement] Make all installed color schemes of console accessible, please

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#158]
Please include all installed color schemes in the console menu.

Compare:
![image](https://user-images.githubusercontent.com/6339921/215741654-dc44a616-c149-4dcf-a383-c16f61b1028c.png)

![image](https://user-images.githubusercontent.com/6339921/215740988-e916dac3-f5bc-4446-beaf-d67e78275a0f.png)

**Comment by l0drex** [comment]
Do you know where these other themes are installed? I currently only check `/usr/share/konsole`.

**Comment by noyannus** [comment]
They're in `~/.local/share/konsole`.

**Comment by l0drex** [comment]
Fixed with #163 - thanks @flying-sheep !
