### ISSUE TITLE
konsoleprofile colors='<theme> ' not working when called from Y&Y

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#160]
I'm trying to include the console colors in the theme switches, to no avail. The Console plugin has no effect here.

`konsoleprofile colors='<theme>` works when called from console or yakuake, or in a script that is run there.

It does not work when called from Y&Y's Custom plugin, nor in a script called from there, no matter whether the Console plugin is active or not.

How can `konsoleprofile colors='<theme>` be used from within Y&Y, if necessary via external script?

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.15.89-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by l0drex** [comment]
Oh wow, I didn't know this even existed! I currently change the profile settings file, which requires a restart of the application.

I tried this with opening two Konsole windows at the same time. Executing the command in one didn't affect the other window at all. Maybe this only affects the current session / window?

**Comment by l0drex** [comment]
Ok, found the source file [here](https://invent.kde.org/utilities/konsole/-/blob/master/tools/konsoleprofile). It particularly sais:
>NOTE: This script MUST run within a konsole tab to take effect. The change is applied only to current tab. Other tabs using the same profile will not be influenced.  Any changes won't be saved to to disk.

**Comment by noyannus** [comment]
Maybe there is a workaround involving
```
[UiSettings]
ColorScheme=
```
in `/home/tw/.config/konsolerc` ? 
No idea, just speculating..

**Comment by noyannus** [comment]
Bad workaround: duplicate active profile with changed color scheme, and activate it then --?

**Comment by l0drex** [comment]
> Maybe there is a workaround involving
> 
> ```
> [UiSettings]
> ColorScheme=
> ```
> 
> in `/home/tw/.config/konsolerc` ? No idea, just speculating..

Might work, but this might also relate to the qt theme. 

The best solution would be upstream support for this, by reloading the profile config if changes are detected.

**Comment by noyannus** [comment]
Thanks for looking into it!

**Comment by noyannus** [comment]
I've wasted some more time on it...
Going through DBus should work for all open console windows.
(Here with a custom dark profile, because of its custom color scheme.)
```
#! /usr/bin/sh

# ===============================================================
# Set Konsole profile for all sessions
# set profile
PROF='Breath Dark (new)'

# loop: console processes
for PROCID in $(pgrep konsole -u $USER) ; do
    SESSIONS=$(qdbus org.kde.konsole-$PROCID | grep 'Sessions/')
    # loop: process sessions
    for SESS in ${SESSIONS}; do
        # set profile
        qdbus org.kde.konsole-$PROCID $SESS \
        org.kde.konsole.Session.setProfile "$PROF"
    done
done
# ===============================================================
```
Possibly related to https://github.com/oskarsh/Yin-Yang/issues/154.
