### ISSUE TITLE
Path to external script in `Custom` plugin needs escaping or something

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#164]
Calling a script from the Custom plugin does not work if the path to it contains a space (and other problematic characters?).
```
$ yin-yang --toggle
<snip>
Traceback (most recent call last):
<snip>
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file:///home/<user>/Documents/<ONLY-FIRST-word-of-filename>'
<snip>
```

**Comment by noyannus** [comment]
The custom plugin seems to split at spaces because it assumes the field content to be a command, possibly followed by arguments that need to be split, right? That collides with field content meant to be a path, and not to get split.

So I see three possibilities: 
- It's either command or path, and the user needs an info what is available,
- a different parsing of commands, or
- a menu/switch/checkbox to tell Y&Y to treat field content as command as path to script, executable, etc..

**Comment by l0drex** [comment]
It might be enough to use `subprocess.run(command, shell=True)`. Tested in the python shell and seems to work
