### ISSUE TITLE
 `yin-yang --toggle` unsets "Automatic theme switching"

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#165]
After a `yin-yang --toggle` the "Automatic theme switching" is **un**set, if Y&Y was closed at that time.

**Comment by l0drex** [comment]
Yes, that's expected. The idea with that option is that the theme switch could be handled externally.

Use ` yin-yang --toggle --systemd` to avoid that. It is a little hack for the systemd service

**Comment by noyannus** [comment]
Can't it just do the switch from console but keep the readiness for automatic switching alive in the background? Would remove the need to manually turn it on after testing. Maybe not worth the hassle, though?

**Comment by l0drex** [comment]
Ah sorry, I changed the command to `yin-yang --systemd` at some point. So, just call `yin-yang --systemd` to simulate what the background job would do: change the theme, don't touch any configuration.

**Comment by noyannus** [comment]
Cool! Thanks!
