### ISSUE TITLE
KDE terminals problem

### ISSUE THREAD

**Issue by bphd** [oskarsh/Yin-Yang#170]
Stills nothing done about #147

**Comment by oskarsh** [comment]
Hey there! When you're submitting an issue on our GitHub page, could you please stick to the main discussion and avoid opening new tickets? 

Also, just a friendly reminder that this project is maintained by volunteers, so updates may take some time and certain features may not be available yet. 

Regarding your specific problem, have you tried defining your desired behaviour as a shell script and calling it with the custom scripts function found in the settings? This might help here. Feel free to share these scripts with the community this makes it easier for us or anyone to build this feature.
