### ISSUE TITLE
path to kdedefaults invalid

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#171]
The path to kdedefaults is invalid. 
(BTW, does this parse as 
`[Invalid object] [path: //home/<user>/.config/kdedefaults/kdeglobals]`, or
`[Invalid object path:] [//home/<user>/.config/kdedefaults/kdeglobals]`?)

```
$ yin-yang --toggle
No such schema “org.gnome.gedit.preferences.editor”
Successfully applied the color scheme BreathDark to your current Plasma session
QDBusConnection: error: could not send signal to service "" path "//home/<user>/.config/kdedefaults/kdeglobals" interface "org.kde.kconfig.notify" member "ConfigChanged": Invalid object path: //home/<user>/.config/kdedefaults/kdeglobals
```

**Comment by l0drex** [comment]
If the theme changes correctly, then that is just the bug in `lookandfeeltool` I reported [here](https://bugs.kde.org/show_bug.cgi?id=432901).
