### ISSUE TITLE
Automatic location time is different from manually set

### ISSUE THREAD

**Issue by alexandervnuchkov** [oskarsh/Yin-Yang#178]
The manually entered location displays different sunset/sunrise time than the automatically detected location.

I tried this on Kubuntu 22.04 LTS and 22.10, and the result is the same. I enter the latitude/longitude values from https://ipinfo.io/loc:

![20230327_110526](https://user-images.githubusercontent.com/12795158/227881429-74fd8eee-49c9-42a6-997c-e4a695acdf78.png)

and the displayed theme change time is correct.

But, when I switch to **update automatically**, the sunset/sunrise time changes to some incorrect values:

![20230327_110534](https://user-images.githubusercontent.com/12795158/227881392-3bdf1591-9ffc-4c32-8702-315f2531be7c.png)

Is this a bug or is it possible to set the location provider somewhere for better results of the automatic location detection?

**Comment by l0drex** [comment]
The automatic location fails and sets 0,0 as you coordinates. I guess you are missing a qt positioning Backend.

**Comment by alexandervnuchkov** [comment]
```bash
libqt5positioning5 is already the newest version (5.15.3+dfsg-3).
```

Should there be something else?

**Comment by l0drex** [comment]
I guess you need geoclue

https://doc.qt.io/qt-6/qtpositioning-plugins.html

**Comment by alexandervnuchkov** [comment]
```bash
geoclue-2.0 is already the newest version (2.5.7-3ubuntu3).
```

I guess I'm missing something else.

**Comment by l0drex** [comment]
I think the issue is that Qt 6 doesn't support the geolocation yet. I tried using Qt 5 for that, but that didn't work either. Guess we have to wait until they resolve that.
