### ISSUE TITLE
v3.2.4-beta misses some settings.

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#180]
v3.2.4-beta does not catch 

- toolbars in konsole,

- tabbar and titlebar in yakuake

- profile of dolphin's terminal pane.

No idea how to approach these. (( 

Dolphin has no `setProfile` in `qdbus org.kde.dolphin-$(pgrep dolphin -u $USER)`.

![2023-04-11_11-04-05](https://user-images.githubusercontent.com/6339921/231117919-82ef03c7-29c8-4322-a69a-43a35ee3f202.png)

![2023-04-11_11-04-15](https://user-images.githubusercontent.com/6339921/231117920-3a3f617c-dd27-454b-a593-57a0cb08e0af.png)

**Comment by l0drex** [comment]
Uhm, I do have a setProfile for dolphin. It's exactly where it is for yakuake and konsole, will add it in the next beta release. 

Toolbars in Konsole should just be handled by the global theme (system plugin), but it looks like the icons are buggy in your screenshot.

Yakuake is a different story, but it doesn't have many themes (at least by default), so it's no priority for me. At first glance, I couldn't find a config file or dbus interface.

**Comment by l0drex** [comment]
Yakuake was requested in #113, so I will close this with the next release

**Comment by noyannus** [comment]
Dolphin, that's strange. Must be a different system or installation.
```
$ qdbus org.kde.dolphin-30323 | grep profile
$ qdbus org.kde.konsole-26105 /Sessions/1 | grep profile
method Striking org.kde.konsole.Session.profile()
method void org.kde.konsole.Session.setProfile(QString profileName)
```
----
The Konsole toolbar issue may have been caused because I set the system them for light and dark *both* to Breeze (to keep the window decorations) and set the others via the other plugins and script. I'll wait for the next release to see if that's still necessary.

**Comment by l0drex** [comment]
I'm using Dolphin version 22.12.3, Konsole the same.

**Comment by noyannus** [comment]
Same versions here.

Konsole toolbar: @adrium has the solution in [nightadjuster]([url](https://github.com/adrium/knightadjuster/blob/master/knightadjuster)). The window color profiles need their own setting loop.

**Comment by l0drex** [comment]
Dolphin only has the session path if the Konsole panel is actually opened.
