### ISSUE TITLE
`yin-yang --toggle` in v3.2.4-beta unsets automatic switching

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#181]
v3.2.4-beta does unset automatic theme switching _when YY is closed_ during a `yin-yang --toggle`.

**Comment by l0drex** [comment]
The toggle option is supposed to do that, since it changes the theme manually. Use `--systemd` to force-apply the theme that should be set by the automatic option.

Or do you want a way to override the current theme without switching to manual?

**Comment by LHLaurini** [comment]
> Or do you want a way to override the current theme without switching to manual?

An option to toggle while keeping automatic switching enabled would be useful.

**Comment by noyannus** [comment]
> Or do you want a way to override the current theme without switching to manual?

The automatic settings (times/sunset/etc) should be left unchanged and the automatic action activated, so that after playing with manual settings (plugins, themes, scripts) one does not have to set them again.
