### ISSUE TITLE
[solved, possibly install bug] Need help setting up timer

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#183]
EDIT. Found the cause: 

`yin_yang.service` and `yin_yang.timer` are copied into a non-root directory (`~.local/share/systemd/user/`), but with owner `root`.

Install script should not change owner.

-----

---- vvv solved vvv ---

I can't get the timer to work. Please point me to a solution.

Installation was done with this script:

```
#! /usr/bin/bash

# Installs the latest Yin-Yang from its GitHub repo.


# download
cd ~/Applications/
git clone https://github.com/oskarsh/Yin-Yang
cd ~/Applications/Yin-Yang 

# Create virtual environment for pypi packages
python3 -m venv .venv
source .venv/bin/activate

# Install pip requirements
pip3 install -r requirements.txt

# Install Yin-Yang
./scripts/install.sh
```
Now I have `yin_yang.service` and `yin_yang.timer` in `~/.local/share/systemd/user/`, a binary (`/usr/bin/yin-yang`), a user unit

![2023-04-12_15-04-17](https://user-images.githubusercontent.com/6339921/231470439-0554248b-85eb-4561-bbed-78dbdfd61545.png)

, and a timer.

![2023-04-12_15-04-58](https://user-images.githubusercontent.com/6339921/231470544-656676cc-3a90-43ee-8450-8699b09a7e93.png)

But setting a custom time in YY does not change `~/.local/share/systemd/user/yin_yang.timer`, and the timer does not change from its bizarro "Next" datetime. 

Where's my snafu?

**Comment by l0drex** [comment]
I am not very confident with bash, any help would be appreciated. Basically the problem is that the install script needs to be run as sudo to install the app in `/etc`. However, when we copy the file as root, the file owner is root.
So I guess what we need to do is:
1. Ensure user is not root
2. Do user stuff
3. Ask for sudo permissions
4. Do root stuff (install app by copying the files)

**Comment by noyannus** [comment]
Or (not tested):
```
#! /usr/bin/sh

sudo su
	<system install>
exit

<user install>

```
The order of regular and root user is not relevant. It also would allow root to have their own user install, if they want.

**Comment by noyannus** [comment]
Or do the necessay `chown`s after the user installation.

**Comment by l0drex** [comment]
I have simply removed the installation of the systemd files from the script all together, since the python scripts create them as well

**Comment by noyannus** [comment]
Does it work if expected? Then we can close this issue. :)
