### ISSUE TITLE
Okular plugin

### ISSUE THREAD

**Issue by l0drex** [oskarsh/Yin-Yang#196]
### What is the plugin for?

Changes the accessibility color mode of Okular

### Why do you need it?

- [x] Application does not offer automatic theme-change
- [ ] Implemented auto-theme doesn't work

### How can the theme be changed?

There is a dbus interface:
https://gitlab.com/LADlSLAV/yabotss/-/blob/main/darkman_examples_kde_plasma/dark-mode.d/10_set_theme_okular_dark.sh

**Comment by l0drex** [comment]
This is about changing the colors of documents via the accessibility settings, not the interface.

**Comment by rokejulianlockhart** [comment]
Oh, brilliant.
