### ISSUE TITLE
Support Snap.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [oskarsh/Yin-Yang#209]
### Describe the bug

My rationale is available at https://github.com/safing/portmaster-packaging/issues/45#issue-961633238:~:text=packages%20for%20snap%20are%20able%20to%20be%20distributed%20without%20necessitating%20containerization.

### Additional notes

https://forum.snapcraft.io/t/yin-yang/35552?u=beedellrokejulianloc

**Comment by rokejulianlockhart** [comment]
https://github.com/oskarsh/Yin-Yang/issues/208#issuecomment-1584847206

**Comment by RokeJulianLockhart** [comment]
> https://github.com/oskarsh/Yin-Yang/issues/209#event-9487748385

@l0drex, please add https://github.com/oskarsh/Yin-Yang/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

**Comment by l0drex** [comment]
I don't plan to create a snap package, flatpak should be enough.
