### ISSUE TITLE
Yin-yang can't ignore `//` aka comments in the config of vscode

### ISSUE THREAD

**Issue by willbasky** [oskarsh/Yin-Yang#213]
### Describe the bug
Yin-yang doesn't switch a theme of vscode. The error is
```python
KeyError: 'autogenerated'
    self.set_theme(theme)
    raise ValueError(f'Theme \"{theme}\" is invalid')
  File "/opt/yin-yang/src/plugins/vscode.py", line 98, in set_theme
ValueError: Theme "" is invalid
    raise e
  File "/opt/yin-yang/src/plugins/vscode.py", line 86, in set_theme
    settings = json.load(sett)
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 5 (char 214)
```
I found out it that `yin-yang` couldn't ignore `//` aka comments in the config of vscode. If I remove one comment it fails with another one. If I remove all comments, it works.

### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [ ] Atom
- [x] Brave
- [x] Colors
- [ ] Custom Script
- [x] Firefox
- [ ] Gedit
- [x] GTK
- [x] Konsole
- [ ] Kvantum
- [ ] Only Office
- [x] System
- [x] VSCode
- [ ] Wallpaper

### Affected versions

- Yin-Yang version: 3.2
- VScode: 1.79.2
- Python version:  3.11.3
- Qt version: 5.15.9

**Comment by l0drex** [comment]
Thats a known issue, see #120
