### ISSUE TITLE
Could not find a version that satisfies the requirement PySide6==6.4.1

### ISSUE THREAD

**Issue by bphd** [oskarsh/Yin-Yang#219]
### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [ ] Atom
- [ ] Brave
- [ ] Colors
- [ ] Custom Script
- [ ] Firefox
- [ ] Gedit
- [ ] GTK
- [ ] Konsole
- [ ] Kvantum
- [ ] Only Office
- [ ] System
- [ ] VSCode
- [ ] Wallpaper

### Affected versions

- Yin-Yang version:

- Relevant application version:
- Python version:
- Qt version:

### Additional notes

cd && sudo apt update && sudo apt install libsystemd-dev gcc pkg-config python3-dev && git clone https://github.com/oskarsh/Yin-Yang; cd Yin-Yang && python3 -m venv .venv && source .venv/bin/activate && pip3 install -r requirements.txt && ./scripts/install.sh
ERROR: Could not find a version that satisfies the requirement PySide6==6.4.1 (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for PySide6==6.4.1 (from -r requirements.txt (line 3))

**Comment by l0drex** [comment]
Current version is 6.5.3, should be fixed with the next release

**Comment by bphd** [comment]
> Current version is 6.5.3, should be fixed with the next release

fixed?
