### ISSUE TITLE
add `--help` and `-h` and `man`

### ISSUE THREAD

**Issue by bphd** [oskarsh/Yin-Yang#221]

**Comment by l0drex** [comment]
`--help` and `-h` should already exist. I don't think man pages are necessary, as the command line options are already explained and rather simple

**Comment by bphd** [comment]
Here are several reasons for including both:

1. **Accessibility**: Different users have varying preferences when it comes to accessing documentation. Some users prefer quick access to essential information via `--help`, while others may prefer a more detailed, comprehensive reference like a `man` page.

2. **Quick Reference vs. In-Depth Information**: The `--help` option is ideal for quick reference, providing essential usage and option information at a glance. On the other hand, the `man` page offers a more comprehensive and detailed explanation of the command's functionality.

3. **Usage Reminders**: Users can quickly check the `--help` output to remind themselves of the basic command syntax and available options without navigating the `man` page.

4. **Beginner-Friendly**: The `--help` option is often more approachable for beginners who may find `man` pages overwhelming. It serves as a user-friendly entry point.

5. **Scripting and Automation**: Script developers can use the `--help` option to extract usage information programmatically, while the `man` page provides detailed guidance for more complex scripting scenarios.

6. **Interactive Exploration**: Users can interactively explore the command's options and behavior using `--help` without leaving their terminal, allowing for trial and error.

7. **Standard Convention**: Many command-line tools adhere to the convention of providing a `--help` option for basic information, making it a familiar and expected feature.

8. **Offline Access**: The `man` page is useful for offline access, as it doesn't require an internet connection to access detailed documentation.

9. **Long-Term Reference**: Users can save `man` pages for long-term reference, making them available even when the software or its online resources change or disappear.

10. **Comprehensive Documentation**: The `man` page can include more than just usage information, such as background, examples, advanced usage, and troubleshooting tips.

11. **Advanced Users**: Advanced users who require in-depth knowledge or who are troubleshooting complex issues can turn to the `man` page for comprehensive documentation.

12. **Community Contribution**: Enthusiastic users or developers can contribute to improving the `man` page, ensuring it remains up-to-date and accurate.

In summary, providing both a `--help` or `-h` option for quick, essential information and a separate `man` page for comprehensive documentation caters to the diverse needs and preferences of users. It offers accessibility and flexibility, ensuring that users at different skill levels and with various requirements can effectively use the command-line utility or software.

**Comment by oskarsh** [comment]
closed due to low quality chatgpt response
