### ISSUE TITLE
System wide switch?

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#224]
Is it possible to have a system wide effect? If not, can we have one?
Pretty pritty pleeeeeeeeeze!

Below is from an installation as regular user:

![image](https://github.com/oskarsh/Yin-Yang/assets/6339921/7f76347f-f2b6-48ae-9fc3-5afdcd07b917)

(Ignore that the editor is not switched -- that's a different wish.)

**Comment by l0drex** [comment]
I think generally you shouldnt start kate as root user. If you want to edit system files, you can open them as you would normally. On save, you will be prompted to enter your password.

**Comment by noyannus** [comment]
Absolutely! This was only a demo to show that Y-Y does not effect changes for root (here, the toolbar).

**Comment by noyannus** [comment]
A theoretical workaround:
Install Y-Y as root, for all users. The latter `~/.config/yin_yang/yin_yang.json` would be links to `/root/.config/yin_yang/yin_yang.json` that has to allow read access.
