### ISSUE TITLE
Update NumPy due to support Python 3.12

### ISSUE THREAD

**Issue by FlyinPancake** [oskarsh/Yin-Yang#225]
### Describe the bug

Yin-Yang uses a NumPy version that depends on the `distutils` package. It is deprecated and removed as of Python 3.12.
### Affected versions

- Yin-Yang version: master

- Python version: 3.12

### Additional notes
As a workaround, python 3.11 can be used as of now.

**Comment by l0drex** [comment]
I have enabled dependabot, that should help with issues like these. Update will follow shortly

**Comment by l0drex** [comment]
Actually, I think we don't even have NumPy as a dependency.
