### ISSUE TITLE
Konsole plugin does not set konsole's window part

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#240]
### Describe the bug

When I set window decorations in konsole, the command throws an error but works; the decorations change. 

Issuing exactly the same (copy-pasted) command in a script in Y&Y's Custom plugin, nothing happens. 

All other settings in the script do work, so the script is called correctly. What is this with window decorations? 

(This may look not strictly a Y&Y issue currently, but if solved will make further plugin development easier.)
```
localhost% WinDec="Breeze"  &&  echo $WinDec
Breeze
localhost% /usr/libexec/kwin-applywindowdecoration ${WinDec}
kf.coreaddons: KPluginFactory could not create a KDecoration2::DecorationThemeProvider instance from "/usr/lib64/qt5/plugins/org.kde.kdecoration2/breezedecoration.so"
Successfully applied the cursor theme Breeze to your current Plasma session
```

(Before testing, check if your OS has `/usr/lib/` instead of` /usr/libexec/`.)

- Yin-Yang version:  3.3

Operating System: openSUSE Tumbleweed 20231121
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.2-1-default (64-bit)

**Comment by noyannus** [comment]
Another observation: the Konsole plugin has no effect. 

I set it to `One Dark `for the Light settings, and to` Breeze Light `for the dark settings, to clearly see the expected changes.

But the Konsole area follows the general light and dark appearance instead of the expected opposite. Even when the plugins `System`, `Colors` and `GTK` are switched off.

**Comment by noyannus** [comment]
So a command is gone from qdbus.

`
org.kde.konsole.Window.setProfile` is gone, at least here on SUSE Tumbleweed.
```

localhost% qdbus org.kde.konsole-21560 /Windows/1 | grep profile
method int org.kde.konsole.Window.newSession(QString profile)
method int org.kde.konsole.Window.newSession(QString profile, QString directory)
method QStringList org.kde.konsole.Window.profileList()
method void org.kde.konsole.Window.setDefaultProfile(QString profile)
```

**Comment by l0drex** [comment]
So in other words, the konsole plugin crashes, which in turn means that the cutom script is never executed?

Can you verify that by doing the following:
1. Disable the konsole plugin
2. Run ` yin-yang --toggle` from the command line
3. Check for any errors in the terminal and post them here, also please tell if your command now works.

**Comment by noyannus** [comment]
The plugin throws no errors.

It works partly, see screenshots. `yin-yang --toggle` sets the session part of konsole, but not the window part. 

I'll edit the title accordingly. 
(Why it did not do anything before is beyond me. Probably my snafu with the script..)

Start with Light theme
![Screenshot_20231124_185215](https://github.com/oskarsh/Yin-Yang/assets/6339921/c2ee40fc-cb8a-42a5-a51b-07f85c79bfa6)

After Light > Dark
![Screenshot_20231124_185230](https://github.com/oskarsh/Yin-Yang/assets/6339921/484c767d-afff-4305-9d65-1440d031b937)

After Dark > Light
![Screenshot_20231124_185254](https://github.com/oskarsh/Yin-Yang/assets/6339921/1b2b3eaf-7117-472d-ab6c-f98ca3cf3ca9)


Start with a dark theme for window
![Screenshot_20231124_185336](https://github.com/oskarsh/Yin-Yang/assets/6339921/1c9089c9-2374-4930-8433-ac2e523103c0)

After Dark > Light
![Screenshot_20231124_185404](https://github.com/oskarsh/Yin-Yang/assets/6339921/75a618c8-86a5-4a18-a12b-477f0958e808)

After Light > Dark
![Screenshot_20231124_185424](https://github.com/oskarsh/Yin-Yang/assets/6339921/3567fcf7-79d8-415f-ab82-b71eb4146161)


Looking for a possible cause I found that qdbus no longer supports `setProfile`.


HTH

**Comment by l0drex** [comment]
The window decorations of konsole can be changed with the system plugin. Does that work for you? Or do you want to change Konsole on its own, with the rest of the system remaining in its current mode?

**Comment by noyannus** [comment]
One night to cool the machine, and one reboot later, I cannot reproduce what I have documented above. Konsole switches as expected. 

So that must have (had?) a cause on my side. My apology for wasting your time.
