### ISSUE TITLE
Too many icons in system tray

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#241]
### Describe the bug

Every time Y&Y is launched, another icon appears.
![image](https://github.com/oskarsh/Yin-Yang/assets/6339921/ada85e2b-70fa-4c94-9807-f928dcc6196a)

### Affected versions

Yin-Yang version: 3.3
Operating System: openSUSE Tumbleweed 20231121
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.2-1-default (64-bit)

**Comment by chase9** [comment]
How were you launching the app?

**Comment by noyannus** [comment]
Manually, with KDE Application Launcher 2.0 in the panel.

Every time I open Y&Y, another icon appears in the same moment as the Y&Y window.

Icons do not survive a logout.

**Comment by noyannus** [comment]
OK. I can live with that. Thank you!




closing as resolved
