### ISSUE TITLE
konsole: toggling night/day doesn't work for new tab

### ISSUE THREAD

**Issue by mirsella** [oskarsh/Yin-Yang#250]
### Describe the bug
when toggling day/night theme in yin-yang, all the already opened konsole or yakuake window will have their profile changed to the right one, but opening new tab in theses app will not be set to the right profile as the default profile isn't updated until restarting the app.

### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [ ] Atom
- [ ] Brave
- [X] Colors
- [ ] Custom Script
- [X] Firefox
- [ ] Gedit
- [X] GTK
- [X] Konsole
- [ ] Kvantum
- [ ] Only Office
- [X] System
- [ ] VSCode
- [ ] Wallpaper

### Affected versions

- Yin-Yang version: yin-yang-git 3.3.r9.gde1f3eb-1 (arch)

- Relevant application version[^1]: kde plasma 5 (same on beta 6)
- Python version: 3.11.6
- Qt version: 6.6.1-1

**Comment by Seas0** [comment]
#280 should fix this
