### ISSUE TITLE
Application does not start because of ValueError when converting coordinates from ipinfo.io to floats

### ISSUE THREAD

**Issue by dospes** [oskarsh/Yin-Yang#253]
### Describe the bug
When trying to start the application using the .desktop file or through the terminal with the venv activated, the application will not start. There is no GUI visible. When trying to start the application from the terminal, I get the following traceback:
I have uninstalled and reinstalled the application using the packaged scripts, the error happened before and after the reinstall.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/yin-yang/yin_yang/__main__.py", line 134, in <module>
    window = main_window_connector.MainWindow()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 55, in __init__
    self.load()
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 89, in load
    self.load_times()
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 95, in load_times
    time_light, time_dark = config.times
                            ^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/config.py", line 455, in times
    latitude, longitude = self.location
                          ^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/config.py", line 426, in location
    coordinate = get_current_location()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/config.py", line 142, in get_current_location
    loc: [float] = [float(coordinate) for coordinate in loc_response]
                    ^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '{\n  "status": 429'
```

### Affected versions

- Yin-Yang version:
Commit de1f3eb5c81f90657685503eb317e1fe91c57273
- Python version: 3.12.0
- Qt version: qt5: 5.15.11, qt6: 6.6.0

### Additional notes
My system is Fedora 39 with KDE Plasma 5.27.9.
This issue is first and foremost for completeness sake, I may be able to delve into the bug myself, but not at this time. In case anyone else is interested in exploring this or has the same issue please go ahead and see if you can find the cause and fix it.

**Comment by EricL521** [comment]
Alright, I looked into it a little bit, it appears that the value of loc_response is `['{\n  "status": 429', '\n  "error": {\n    "title": "Rate limit exceeded"', '\n    "message": "You\'ve hit the daily limit for the unauthenticated API.  Create an API access token by signing up to get 50k req/month."\n  }\n}']`

What worked for me is adding this line of code before the line where the error was (config.py line 142):  `if len(loc_response) != 2: return QGeoCoordinate(0, 0)`, rerunning the installation script, and then turning off update location automatically and putting my location in manually
