### ISSUE TITLE
Yin Yang will not open due to a dictionary key error.

### ISSUE THREAD

**Issue by MelodyTrailGH** [oskarsh/Yin-Yang#259]
### Describe the bug
When trying to open Yin Yang the program will instantly crash. From the Traceback error is says `KeyError: 'Default Light+'` which is a pre-existing and default theme in Visual Studio Code. I tried to find a config file to disable the plugin (via deleting `$HOME/.config/yin-yang`) but the issue still persists. 

### Enabled plugins

What plugins did you have enabled? If not relevant, you can remove this.

- [ ] Atom
- [ ] Brave
- [x] Colors
- [ ] Custom Script
- [x] Firefox
- [ ] Gedit
- [x] GTK
- [x] Konsole
- [ ] Kvantum
- [ ] Only Office
- [x] System
- [x] VSCode
- [ ] Wallpaper

### Affected versions

- Yin-Yang version: v3.3
- Relevant application version[^1]: Visual Studio Code v1.85.1
- Python version: 3.11.6
- Qt version: qt6

[^1]: This refers to the application a plugin might use. For example, if you submit a bug report for the Firefox plugin, this refers to the Firefox version you are using. If the bug is in a plugin for a desktop environment, this refers to the DE (Plasma, Gnome, etc).

### Additional notes
Yin Yang will work perfectly fine on other user profiles besides mine. Though those users don't have Visual Studio Code installed.

**System Information:**
* Operating System: Arch Linux x86_64
* Kernel: 6.6.9-zen1-1-zen
* Desktop Environment: Plasma 5.27.10
* Window Manager: Plasma 5.27.10

### Log
```
Using default configuration values.
No such schema ?org.gnome.gedit.preferences.editor?
/opt/yin-yang/main.py:65: DeprecationWarning: Function: 'QLibraryInfo.location(QLibraryInfo.LibraryPath location)' is marked as deprecated, please check the documentation for more information.
  path = QLibraryInfo.location(QLibraryInfo.TranslationsPath)
2024-01-06 06:46:22,395 ERROR - root: Error while loading application translations!
Error while loading translation. Using default language.
2024-01-06 06:46:23,198 WARNING - src.plugins._plugin: Used theme is unknown for plugin Colors
2024-01-06 06:46:23,198 WARNING - src.plugins._plugin: Used theme is unknown for plugin Colors
Traceback (most recent call last):
  File "/opt/yin-yang/main.py", line 107, in <module>
    main(args)
  File "/opt/yin-yang/main.py", line 84, in main
    window = main_window_connector.MainWindow()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 56, in __init__
    self.load()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 90, in load
    self.load_plugins()
  File "/opt/yin-yang/src/ui/main_window_connector.py", line 120, in load_plugins
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/src/plugins/_plugin.py", line 76, in get_widget
    for inp in self.get_input(widget):
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/src/plugins/_plugin.py", line 102, in get_input
    inp.setCurrentIndex(themes.index(self.available_themes[theme]))
                                     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'Default Light+'
```

**Comment by MelodyTrailGH** [comment]
Yes they are the new default themes, I've even checked this by installing Visual Studio Code on a brand new machine (with no settings sync) and those are the themes that are available by default.

**Comment by MelodyTrailGH** [comment]
I forgot to add some evidence to my claim that Light+ and Dark+ are in-fact the default themes that come with Visual Studio Code 1.85.1.

Here is a look at the extensions list.
![Screenshot_20240117_174549](https://github.com/oskarsh/Yin-Yang/assets/153487483/3c88ae02-12a7-45cf-8cc0-f3715b71b2ae)
I have no themes or extensions installed and I'm using the Default profile.
![Screenshot_20240117_174651](https://github.com/oskarsh/Yin-Yang/assets/153487483/198f6e9f-3351-4fba-8d2a-87f3420ba8af)

Here is a look at the preferences.
For me the default theme is "Abyss" but Light+ and Dark+ are included as well.
![Screenshot_20240117_174759](https://github.com/oskarsh/Yin-Yang/assets/153487483/52b8f3fc-a8b1-40e8-8adc-efde00e90eb6)

![image](https://github.com/oskarsh/Yin-Yang/assets/153487483/0007b136-dba8-4231-a238-410932a93bf4)

**Comment by l0drex** [comment]
Huh, so you still have Light+ and Dark+ installed. Are they available in the dropdown menu? If not, where have you vscode installed?

**Comment by MelodyTrailGH** [comment]
Sorry for taking long to respond, I have Visual Studio Code installed in `/usr/bin/code` as I installed it from the Arch User Repository.
My `.vscode` folder is in my home directory `~/.vscode`.
