### ISSUE TITLE
Yin-Yang wont open EndeavorOS Gnome

### ISSUE THREAD

**Issue by nosar77** [oskarsh/Yin-Yang#267]
### Describe the bug
On the latest EndeavourOS running Gnome (45.3). Program wont run, due to an issue I believe that has to do with the default missing theme that I think endevouros gets rid of? 

### Affected versions

- Yin-Yang version: 3.3.r18.g1d5c01c-1 

- Python version: 3.11.7
- Qt version: 6

[^1]: This refers to the application a plugin might use. For example, if you submit a bug report for the Firefox plugin, this refers to the Firefox version you are using. If the bug is in a plugin for a desktop environment, this refers to the DE (Plasma, Gnome, etc).

### Additional notes

` yin-yang
Plugin Colors has no support for your desktop environment yet!
Plugin Icons has no support for your desktop environment yet!
Using default configuration values.
No such schema “org.gnome.shell.extensions.user-theme”
No such schema “org.gnome.gedit.preferences.editor”
Error while loading translation. Using default language.
No such schema “org.gnome.shell.extensions.user-theme”
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/yin-yang/yin_yang/__main__.py", line 134, in <module>
    window = main_window_connector.MainWindow()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 55, in __init__
    self.load()
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 91, in load
    self.load_plugins()
  File "/opt/yin-yang/yin_yang/ui/main_window_connector.py", line 126, in load_plugins
    widget = plugin.get_widget(self.ui.plugins_scroll_content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/yin-yang/yin_yang/plugins/_plugin.py", line 71, in get_widget
    widget.setVisible(self.available)
TypeError: 'PySide6.QtWidgets.QWidget.setVisible' called with wrong argument types:
  PySide6.QtWidgets.QWidget.setVisible(method)
Supported signatures:
  PySide6.QtWidgets.QWidget.setVisible(bool)
`

**Comment by nosar77** [comment]
Okay update, I noticed it sends problem with translations on the notifications. Maybe its the translations not the theme thats the issue.

**Comment by l0drex** [comment]
Same issue as #261
