### ISSUE TITLE
Doesn't change window manager theme on XFCE

### ISSUE THREAD

**Issue by sudcapitano** [oskarsh/Yin-Yang#288]
### What is the plugin for?
To change the corresponding Xfwm4 theme if there is one. 

### Why do you need it?

- Everything works as expected but there should be an option to change the Xfwm4 theme also. 

### How can the theme be changed?
Right now I just run xfconf-query -c xfwm4 -p /general/theme -s THEME-NAME in the custom script section but I think it would be better to implement it in the actual program. 

### Additional notes
None

**Comment by l0drex** [comment]
What are the default theme names? Is there a way to get a list of installed themes?

**Comment by sudcapitano** [comment]
I am using a theme named Orchis it has a light and dark variant but I would assume it should work with any gtk theme. Not sure how to get a list, but I ended up adding a custom script to change it.

**Comment by l0drex** [comment]
I implemented a plugin using the dbus, it's on the beta branch.
