### ISSUE TITLE
Always version 3.3

### ISSUE THREAD

**Issue by kamikazebob** [oskarsh/Yin-Yang#291]
### What happened?

Trying to install the latest 3.4 update but however way I do it, it always installs v3.3 !

How can I update to 3.4 ?

### Version

3.3

### How did you install Yin & Yang?

Git clone + running install script

### What desktop environments are you seeing the problem on?

KDE

### Which plugin causes the issue?

None

**Comment by l0drex** [comment]
That's because I forgot to update the version number in the GUI xD
It's fixed in the beta branch, see #286

**Comment by l0drex** [comment]
It's an argument for the command-line, so you can add `yin-yang --minimized` as a startup script, for example in KDE settings, and have the tray icon in the task bar.
