### ISSUE TITLE
SystemD does not work/Instructions unclear on enabling.

### ISSUE THREAD

**Issue by WinnerWind** [oskarsh/Yin-Yang#295]
### What happened?

Hi there!
The SystemD for YinYang does not exist as `yin-yang.service` or `yin_yang.service`, or I was not able to find it. It is not clear in the Readme how to enable the systemd service for yin-yang so that the GUI application won't be needed to open on start up.
The Readme should include clear and concise instructions on how to enable the systemd service, and what its name is.

### Version

3.4

### How did you install Yin & Yang?

AUR

### What desktop environments are you seeing the problem on?

other

### Which plugin causes the issue?

None

**Comment by WinnerWind** [comment]
Note 
As per #183 , the service should be `yin_yang.service` and `yin_yang.timer` but they don't exist.
![image](https://github.com/oskarsh/Yin-Yang/assets/71366717/e07e17c5-ceb1-4717-8c9b-bba78db62485)

**Comment by l0drex** [comment]
The app automatically enables the services when you enable the automatic theme change in the gui.

**Comment by l0drex** [comment]
Well they should be named `yin_yang`. The install script should but them in the systemd home directory (sth like `~/.config/systemd/user`)

**Comment by WinnerWind** [comment]
Hi there!
service files are not accessible from the above mentioned folder. 
/etc/systemd/system/ or /usr/lib/systemd/system/ are the correct folders for SystemD units. 
Moving the YinYang files into /etc/systemd/system/ works.

**Comment by l0drex** [comment]
We use user files, so the correct home directory is used. 
So you place your systemd files in the home directory. Yin Yang uses `~/.local/share/systemd/user`, `~/.config/systemd/user/` is valid as well (see man page [`systemd.unit(5)`](https://www.man7.org/linux/man-pages/man5/systemd.unit.5.html)).
Since we are using user units, you need to pass `--user` when activating them. So you use:
```systemctl --user enable yin_yang.timer```
