### ISSUE TITLE
Gnome 46 GTK4 apps are not switching to dark mode and vice versa

### ISSUE THREAD

**Issue by kreon28** [oskarsh/Yin-Yang#297]
### What happened?

I have noticed that switching to dark mode is not working with GTK4 gnome and its apps.
Taking a look at Gnome quick options shows that dark mode is not active. 
![darl(1)](https://github.com/oskarsh/Yin-Yang/assets/79510999/455573e9-192f-4560-8c78-87c52694f610)
Finally, apps like nautilus, system settings etc. are in light mode.
I do not know if it is connected to Arch or not. Tried also with libadwaita without adwaita but that did not change anything.
All GTK3 applications, Kvantum, Firefox work flawlessly. 
To have dark mode in GTK4, I need to manually click dark mode using system switch.  
P.S Switching from dark mode to light mode also need a manually switch.

### Version

3.4-1

### How did you install Yin & Yang?

AUR

### What desktop environments are you seeing the problem on?

Gnome

### Which plugin causes the issue?

GTK

**Comment by l0drex** [comment]
Have you tried using the [Gnome extension](https://extensions.gnome.org/extension/2236/night-theme-switcher/) for auto dark mode? That's what I am using on Gnome. It's lacking all the "glue-code" though to sync apps that don't detect system theme changes that is provided here.

**Comment by kreon28** [comment]
I get it. With that extension it works now. So thanx a lot.
