### ISSUE TITLE
Support for brave-browser

### ISSUE THREAD

**Issue by k4j8** [oskarsh/Yin-Yang#32]
I have created bash scripts to change programs between light and dark mode. I'm listing lines from these scripts with the intention of adding support for these programs once I understand how Yin-Yang is structured. If someone else wants to add it first, be my guest. The commands below have only been tested on Fedora Linux.

To change brave-browser to light mode:
`sed -i 's/"theme":{"type":[[:digit:]],/"theme":{"type":2,/' ~/.config/BraveSoftware/Brave-Browser/Default/Preferences`

To change brave-browser to dark mode:
`sed -i 's/"theme":{"type":[[:digit:]],/"theme":{"type":1,/' ~/.config/BraveSoftware/Brave-Browser/Default/Preferences`

**Comment by daehruoydeef** [comment]
Looks really good and thank you for taking the Time, Yin-Yang is structured really easy and I actually rewritten it so people can more easily contribute. 
To add this functionality to Yin-Yang you will need to create a file brave.py inside the plugins folder that features 2 Functions: `switchToLight` and `switchToDark`.

Implement any custom code in the respected function, for example in your use case you would want to convert this command to a subprocess command that would could look like that (not tested and probably not working just to illustrate): 

`subprocess.run(["sed", "-i", "s/"theme":{"type":[[:digit:]],/"theme":{"type":2,/' ~/.config/BraveSoftware/Brave-Browser/Default/Preferences" ])`

this code bit would go intot the switchToLight Function. The same with the theming set to dark would go into the switchToDark Function.

Finally you will need to call this from the yin-yang.py module.
1. add the Import 
`from src.plugins import kde, gtkkde, wallpaper, vscode, atom, gtk, brave`
2. Inside the Yang thread implement: `brave.switch_to_light()`
3. Inside the Yin thread implement: `brave.switch_to_dark)`

If you need any help regarding this please contact me and i will see if we could make this possible.
