### ISSUE TITLE
does not work at all on Ubuntu MATE

### ISSUE THREAD

**Issue by yerbestpal** [oskarsh/Yin-Yang#35]
* Nothing changes at all, including themes and wallpapers. 
* The scheduler also does not work. 

I have noticed that any changes I makes to yin_yang.json are reset every time I run the application. This means that I cannot change "desktop" from _unknown_ to _gtk_ Also, when running the appimage from the terminal, I get the following output:

```
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
```

I also notice that you are supposed to be able to assign commands to keybinds but I don't see how this is possible since the application is just a portable appimage, and not installed.

**System:** Ubuntu MATE 19.10
**Desktop:** Mate

**Comment by daehruoydeef** [comment]
Currently, Ubuntu MATE is not supported, however it should be pretty straightforward to add support for it. I never ran MATE neither did I tested it on it so I cannot verify if it works.

Adding support should be pretty easy:
[check out this line](https://github.com/daehruoydeef/Yin-Yang/blob/a5c2712e9715d079353fc7f4104eee6b1f09129c/src/config.py#L26)
Basically all you need to do is add a regex for the MATE desktop, the problem I faced is that most Distros implement the name different so for example it could be `mate` or `mate-desktop`.

Regarding the shortcut option indeed it does not work with the AppImage, I would suggest cloning the repository and running
`sudo sh install.sh` that way you will receive more control over the application since AppImage is a contained sandbox of the application.

**Comment by yerbestpal** [comment]
@daehruoydeef That's very helpful, thanks. I'm going to use this as an opportunity to submit my first changes, I just need to get to grips with Git before I do anything about it.

**Comment by daehruoydeef** [comment]
This is a really great first contribution and is much welcome thanks :)

**Comment by yerbestpal** [comment]
> [check out this line](https://github.com/daehruoydeef/Yin-Yang/blob/a5c2712e9715d079353fc7f4104eee6b1f09129c/src/config.py#L26)
> Basically all you need to do is add a regex for the MATE desktop, the problem I faced is that most Distros implement the name different so for example it could be `mate` or `mate-desktop`.

On my Mate system, `echo $DESKTOP_SESSION` returns `mate`. Also, `echo $XDG_CURRENT_DESKTOP` returns `MATE`. So this is just guesswork going off what you said and looking at the code. I otherwise wouldn't have a clue how to implement this:

```python
# create mate regex object
mate_re = re.compile(r'mate')
```

Then add the following if statement:

```python
if mate_re.search(env) or mate_re.search(second_env) or mate_re.search(third_env):
        return "gtk"
```
What do you think? I assume we want to return `gtk` here since mate is gtk.

**Comment by daehruoydeef** [comment]
Yes this looks correct, great work. Feel free to add a pull request I will merge this and update the repository.

**Comment by yerbestpal** [comment]
I'll get on this very soon. I was ready to go before I realised I haven't even tested it.

**Comment by yerbestpal** [comment]
@daehruoydeef I built my fork using `./build/build.sh` and there is an executable in `/Yin-Yang/dist` which does run but doesn't seem to have any affect. Do you have any guidance at all?

**Comment by daehruoydeef** [comment]
What do you mean by have no affect at all? Like does it start (gui shows) and does not work in functionality or does it not even start. Can you show me a screenshot of the generated files. Usually the build process is really dumb. It builds a single file binary with PyInstaller, it packages that up as a .deb file and finally generates a AppImage. I feel like this process should be much more straightforward.
