### ISSUE TITLE
Support for Qt colour schemes.

### ISSUE THREAD

**Issue by baduhai** [oskarsh/Yin-Yang#47]
It'd be nice if you could switch between installed colour schemes, and not just between breeze and breeze-dark.

**Comment by tneo** [comment]
You can already. Start Yin-Yang and click on settings in the top right. There you can pick a theme installed. All themes that are in ~/.local/share/plasma/desktoptheme/ are displayed for me.

**Comment by daehruoydeef** [comment]
I guess he refers to the color schemes found in the system settings dialog, they differ from the Global Theme. 

Right now I have not found a way to change those with the whole os knowing about it, if someone figues out how to read out and change the color scheme I would be really happy.

**Comment by baduhai** [comment]
Perhaps the code for the [colour scheme kcm](https://phabricator.kde.org/source/plasma-desktop/browse/Plasma%252F5.18/kcms/colors/) can provide som insight as to how the colour scheme is set.

**Comment by baduhai** [comment]
[This](https://github.com/maldoinc/plasma-theme-switcher) project may also serve as good reference as to how the colour scheme is set.

**Comment by daehruoydeef** [comment]
Thanks will need to take a deeper look, but looks promising!
