### ISSUE TITLE
Add Changing kde icons

### ISSUE THREAD

**Issue by Da-Viper** [oskarsh/Yin-Yang#50]
you can use the plasma-changeicons 
as the executbale was added in the cmakelist.txt of kcm icons [here](https://github.com/KDE/plasma-desktop/tree/master/kcms/icons

it is not added in PATH by default in kde 
its path is in /usr/bin/plasma-changeicons
or you can use "locate plama-changeicons" to find the path in the distro 

would have made a pull request but don't know c++ to make the ui

script showing how it was used https://github.com/Da-Viper/kde_theme_script/blob/master/dark.sh

**Comment by daehruoydeef** [comment]
You do not need to know c++ to edit the GUI, in fact you will only need to Download QT and QT Designer. Open the UI File, edit it and run the buildUi.py file this will automatically convert the ui into a .py file. There is some manual fixing involved for the image paths.

I will have a look, but currently I am really busy.

**Comment by tneo** [comment]
If you create a global theme, which Yin-Yang uses, than you can set the icon theme in there.

**Comment by l0drex** [comment]
Merging with #177
