### ISSUE TITLE
Integration with Clight

### ISSUE THREAD

**Issue by l0drex** [oskarsh/Yin-Yang#51]
Would be really nice to switch the theme automatically according to environment brightness. This is what [Clight](https://github.com/FedeDP/Clight) can do.

In the Clight wiki, there is a small [example script](https://github.com/FedeDP/Clight/wiki/DE-Integration) to do this.

**Comment by daehruoydeef** [comment]
This is a really nice enhancement. This will need to have a gui option as well and should be optional if you have clight installed.

**Comment by l0drex** [comment]
Actually, the signals clight emits seem to be always on sunrise and sunset.
