### ISSUE TITLE
Force VS Code Window Reload?

### ISSUE THREAD

**Issue by ryanerwin** [oskarsh/Yin-Yang#57]
It's great to update the VS code config to update the theme, but what about forcing VS Code to do the equivalent of <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>P</kbd> `Developer: Reload Window` to actually activate the changed VS Code theme?

**Comment by daehruoydeef** [comment]
I see no possiblity to force reload the vscode window without killing the process and starting a new one. The Theme should be applied anyways there is usually no Reload Window functionality needed.

**Comment by ryanerwin** [comment]
Strange... When I change the theme, only when I reload the window does it actually update.
Good to know that it works instantly for you though!

Thanks!

**Comment by daehruoydeef** [comment]
I have never heard the complaint before so I wonder what setup are you running.
Which distro?
How did u installed vscode?

**Comment by ryanerwin** [comment]
I'm using Ubuntu 20.04.... I installed VScode via the 64-bit .DEB files that are posted directly on the VS Code site.

https://code.visualstudio.com/#alt-downloads

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-33-generic
```

**Comment by daehruoydeef** [comment]
There is currently no way to reproduce this bug for me, if you would like you could try to debug it yourself otherwise you will need to reload the window in vscode.

**Comment by daehruoydeef** [comment]
Is this bug still existing?

**Comment by ryanerwin** [comment]
Toggling the color on VScode seems to be working now, however toggling the color also completely wiped out the other settings I had in VScode... 

now when I use Yin & Yang, `setting.json` is empty except the `workbench.colortheme`

```
 ~/SourceInstall/Yin-Yang   master  code --version
1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
 ~/SourceInstall/Yin-Yang   master  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
```

![vscode-w-yin-and-yang](https://user-images.githubusercontent.com/2156415/100577388-be4bd200-3312-11eb-8bfc-c4ed1d1978ec.gif)

**Comment by daehruoydeef** [comment]
really interesting thanks for pointing that out. I will try to debug further.

**Comment by l0drex** [comment]
Progress on the config file issue will now be tracked in #84
