### ISSUE TITLE
Add a hook

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [oskarsh/Yin-Yang#60]
It would be cool if I could give some terminal commands that can be ran as yin yang changes from dark to light. 

I am using a light and dark mode `userContent.css` and `userChrome.css` for firefox and cronjob/systemd timers are the only other way to achieve switching them on schedule

**Comment by daehruoydeef** [comment]
I am planning a feature where the user can add custom scripts that are executed when the setting is enabled. It is not exactly a hook but should give the same functionality.

**Comment by 416d72** [comment]
@oskarsh Any update on this?
