### ISSUE TITLE
Illegal option - Debian 10

### ISSUE THREAD

**Issue by Gaw18** [oskarsh/Yin-Yang#71]
When I run the command to install it there is the problem that come back.
I have  **Debian 10** with **Kde plasma 5.14.5** with kernel 4.19.0-12-amd64
``install.sh: 3: set: Illegal option -o pipefail``

![yin-yang](https://user-images.githubusercontent.com/61871789/97775826-f9b47e80-1b63-11eb-9159-257ec26425ac.png)

**Comment by daehruoydeef** [comment]
Yes this is to pipefail indicating that the script is wrong, for v2 there will be more solid installation process. You can manually delete this line: `set -euo pipefail`

this will expose the errors to you and shows you what is missing on the system

**Comment by l0drex** [comment]
Same as #86, should work by using `./install.sh` instead of `sh install.sh`
