### ISSUE TITLE
Support XFCE

### ISSUE THREAD

**Issue by berbiche** [oskarsh/Yin-Yang#72]
Supporting XFCE is as simple as:

``` console
$ xfconf-query -c xsettings -p /Net/ThemeName -s 'Adwaita'
$ xfconf-query -c xsettings -p /Net/ThemeName -s 'Adwaita-dark'
```

Thanks for this tool!

**Comment by daehruoydeef** [comment]
Thanks for showing me this, I will add this soon. V3 will feature a GUI but I will add this to the config file before so you can already use this.

**Comment by gitbitfit** [comment]
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-1/workspace0/last-image -s /home/user/Downloads/background.jpg
