### ISSUE TITLE
Typo in config.py - set_sun_time

### ISSUE THREAD

**Issue by fdi438** [oskarsh/Yin-Yang#74]
The automatic switching according to the local sunset / sunrise does not work correctly (gets wrong times).

I have looked into the config.py, and it seems that in set_sun_time, both latitude and longitude values are pulled from the setting fro the latitude (get("latitude")).

**Comment by fdi438** [comment]
Just saw that there's a PR for this
https://github.com/daehruoydeef/Yin-Yang/pull/73#issue-524979851

**Comment by daehruoydeef** [comment]
just merged :)
