### ISSUE TITLE
Option just to change Plasma Style?

### ISSUE THREAD

**Issue by taprobane99** [oskarsh/Yin-Yang#76]
Could an option be made on KDE just to change the Plasma Style?

My global theme, plasma style, icons, and colors are all from a mix of themes, and I just want the style to change but keep the others how i set them.

**Comment by daehruoydeef** [comment]
I do not figured out a way to just change the plasma style. If you have a command that allows to do so I am happy to implement this.

**Comment by IceCloud76** [comment]
https://github.com/maldoinc/plasma-theme-switcher

It seems someone else already has a tool to easily change the plasma style. It could be implemented like how the dev here did, or maybe Yin-Yang could require plasma-theme-switcher as a dependency for this feature?

**Comment by noyannus** [comment]
For a partial answer, see #186.

**Comment by l0drex** [comment]
Merging this with #177
