### ISSUE TITLE
where can I set sunset ?

### ISSUE THREAD

**Issue by spphinslove** [oskarsh/Yin-Yang#78]
Does it can automatic detect location？

**Comment by l0drex** [comment]
You can enable dark mode at night in the config file (`~/.config/yin_yang/yin_yang.json`). Change `follow_sun` and `schedule` to `True` and put in your coordinates in `latitude` and `longitude`.

You can get your coordinates with websites like [ipinfo](https://ipinfo.io/loc).

**Comment by l0drex** [comment]
If this solved your problem, please close this issue.
