### ISSUE TITLE
GTK applications don't update

### ISSUE THREAD

**Issue by drexfall** [oskarsh/Yin-Yang#79]
**Distro:** Manjaro 64bit X11
**Environment:** KDE Plasma 5.21

**I have already read the Troubleshooting page** and tried the mentioned way to solve the issue but it still persists. Applications like FireFox, Pamac Package Manager and several other GTK applications **do** react to live theme change _(change of theme without restarting the application)_ when done from inside the System Settings, but Yin-Yang for some reason doesn't seem able to do that. **After restarting the GTK application,** the theme changes get applied just fine but I have to lose all my active tabs in order to do so.

Also, when run from the terminal, I get this error:
![image](https://user-images.githubusercontent.com/67905454/113469283-0702cb80-946a-11eb-95f1-533701dbbea4.png)

**Comment by l0drex** [comment]
> Also, when run from the terminal, I get this error:

This error comes from the cli tool that is used to change the KDE theme. See the bug report [here](https://bugs.kde.org/show_bug.cgi?id=432901). It shouldn't be a problem.

Do you use custom themes or the standard KDE Breeze theme for GTK?

**Comment by shreyash** [comment]
I use Manjaro KDE which has the Breath themes _(a refresh of Breeze themes I suppose)_ preinstalled. I use the dark and light variants of the same.

**Comment by l0drex** [comment]
You can try to use the Breeze Gtk theme. It uses the colors from the Qt theme and updates itself correctly. Therefore you do not have to use Yin Yang for the Gtk theme.

On Manjaro it's not installed by default, you can install it from pamac. It's called `breeze-gtk`.
