### ISSUE TITLE
I find a bug.When KDE change global theme,the icon settting will be reset.

### ISSUE THREAD

**Issue by spphinslove** [oskarsh/Yin-Yang#83]
Now everytime yin-yang auto switch  dark or light theme,the icon theme will set to default theme.Hope can fix this issues.

**Comment by l0drex** [comment]
The global theme included the icon theme, so if you change the global theme to Breeze, the Breeze icon theme will be use, too.
You can work around this by creating your own global theme with the icon theme you want to use.

**Comment by spphinslove** [comment]
> 
> 
> The global theme includes the icon theme, so if you change the global theme to Breeze, the Breeze icon theme will be used.
> You can work around this by creating your own global theme with the icon theme you want to use.

I modify the theme config file,it worked

**Comment by l0drex** [comment]
> I modify the theme config file,it worked

Great! If you dont have any remaining questions, you can close this issue.
