### ISSUE TITLE
Crashing on Clicking Settings

### ISSUE THREAD

**Issue by erayerdin** [oskarsh/Yin-Yang#98]
The app crashes on clicking "Settings" button. The traceback:

```plain
Traceback (most recent call last):
  File "/opt/yin-yang/src/gui.py", line 173, in open_settings
    self.secwindow = SettingsWindow()
  File "/opt/yin-yang/src/gui.py", line 24, in __init__
    self.sync_with_config()
  File "/opt/yin-yang/src/gui.py", line 94, in sync_with_config
    plugin.available_themes[
KeyError: 'Default Light+'
/usr/bin/yin-yang: line 3:  5465 Aborted                 (core dumped) python3 -O /opt/yin-yang/main.py $@
```

Installed with instructions on README.

***

# Environment

 - Manjaro 21.1.2
 - KDE/Plasma

**Comment by MateusWiteck** [comment]
Same Here, KdeNeon 5.22
KDE Plasma: 5.22.5
KDE Frameworks: 5.85.0
Qt: 5.15.3
kernel: 5.11.0-27-generic (64-bit)

**Comment by l0drex** [comment]
Do you have VSCode installed?

**Comment by Phraqzy** [comment]
It crashes here too with the same message, using on Arch Linux (EndeavourOS) with Plasma 5.22.5

**Comment by erayerdin** [comment]
> Do you have VSCode installed? Where is it installed?

I have it natively installed (no snap or flatpak) [from AUR](https://aur.archlinux.org/packages/visual-studio-code-bin/?O=10&PP=10).

**Comment by l0drex** [comment]
I think I have solved the issue, at least it now works for me :rocket:

**Comment by foemre** [comment]
How did you solve it? Please share

**Comment by l0drex** [comment]
The pull request has not been merged yet by @oskarsh. Unless you are using the branch in my pull request, then nothing changed and the bug is still there.
I recommend waiting until the pull request is merged. This might take a while, so you might want to edit your config at `~/.config/yin_yang/yin_yang.json` directly.
